describe('Create a page draf sin titulo', () => {
    it('Create a page draf sin titulo', () => {
      cy.visit('http://localhost:2368/ghost/#/signin')
      cy.get('.email.ember-text-field.gh-input.ember-view').type('j.cuestaa@uniandes.edu.co')
      cy.get('.password.ember-text-field.gh-input.ember-view').type('hqlDIOPN9j')
      cy.get('.login.gh-btn.gh-btn-blue.gh-btn-block.gh-btn-icon.ember-view').click()
      cy.wait(1000)  
      cy.get('[id$=ember30]').click()
      cy.wait(2000)
      cy.get('.ember-view.gh-btn.gh-btn-green').click()
      cy.wait(3000)  
      cy.get('.gh-editor-title.ember-text-area.gh-input.ember-view').type('{enter}') 
    })
    it('Create a page draf sin titulo', () => {
      cy.visit('http://localhost:2368/ghost/#/signin')
      cy.get('.email.ember-text-field.gh-input.ember-view').type('j.cuestaa@uniandes.edu.co')
      cy.get('.password.ember-text-field.gh-input.ember-view').type('hqlDIOPN9j')
      cy.get('.login.gh-btn.gh-btn-blue.gh-btn-block.gh-btn-icon.ember-view').click()
      cy.wait(1000)  
      cy.get('[id$=ember30]').click()
      cy.wait(5000)
      cy.xpath('/html/body/div[2]/div/main/section/section/ol/li[2]/a[2]/h3').click({force: true})
      cy.wait(2000) 
      cy.get('.koenig-editor__editor.__mobiledoc-editor.__has-no-content').type('Descripcion de la pagina draf sin titulo')
      cy.wait(2000)
      cy.get('.blue.link.fw4.flex.items-center.ember-view').click()
      })
  })